language: go
go:
  - 1.12.x
sudo: false

services:
  - docker

notifications:
  email:
    recipients:
      - yiming.jin@live.com
    on_success: always
    on_failure: always

jobs:
  include:
    - stage: 生产环境打包
      script: 
        - export DOCKER_USER=赚钱的大氓
        - export DOCKER_PASS=6snC9AznJpjWZAw
        - export DOCKER_REPO=registry.cn-hongkong.aliyuncs.com
        - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin $DOCKER_REPO
        - go get -v .
        - go build .
        - python package.py
      if: branch =~ /^(master|release|production|stable).*$/

    - stage: 测试环境打包
      script: 
        - export DOCKER_USER=赚钱的大氓
        - export DOCKER_PASS=6snC9AznJpjWZAw
        - export DOCKER_REPO=registry.cn-hongkong.aliyuncs.com
        - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin $DOCKER_REPO
        - python package.py
      if: branch =~ /^(dev|test|staging).*$/
