FROM golang:latest AS builder
ENV BUILD_DIR=/go/src/github.com/haodiaodemingzi/cloudfeet APP=cloudfeet-config CGO_ENABLED=0 GOOS=linux
RUN mkdir -p $BUILD_DIR
ADD . $BUILD_DIR
WORKDIR $BUILD_DIR/cloudfeet-config
RUN go get -v .
RUN go build -o /tmp/$APP .

FROM alpine:latest
RUN apk --no-cache add ca-certificates bash
COPY --from=builder /tmp/$APP /$APP
RUN chmod +x /$APP
CMD ["/$APP"]
expose 8080 


